class Concert:
    title: str
    date: str
    headliner: str
    venue: str
    age_restriction: str
    price_range: str
    genre: str
    door_time: str
    show_time: str
    ticket_url: str
    image_url: str
